version: '3.8'

services:
  api:
    image: ${DEADLOCK_API_IMAGE:-aboba-telegramovich-api}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - deadlock-storage:/app/apps/api/storage
    environment:
      - DB_HOST=${DB_HOST:-aboba-telegramovich-postgres-1}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-deadlock_builds}
      - DEADLOCK_API_KEY=${DEADLOCK_API_KEY}
      - CHROMIUM_PATH=${CHROMIUM_PATH:-/usr/bin/chromium-browser}
    restart: always
    networks:
      - default
      - aboba-telegramovich_default

volumes:
  deadlock-storage:

networks:
  aboba-telegramovich_default:
    external: true
