import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateRecommendationRuntimeTables1788220800000 implements MigrationInterface {
  name = 'CreateRecommendationRuntimeTables1788220800000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const statements = [
      'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"',
      `CREATE TABLE IF NOT EXISTS "recommendation_item_catalog_versions_v1" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "catalogVersionId" character varying(128) NOT NULL,
        "contentCatalogVersionId" character varying(128),
        "clientVersion" character varying(128),
        "rulesetKey" character varying(128) NOT NULL,
        "source" character varying(64) NOT NULL,
        "payloadSha256" character(64) NOT NULL,
        "importedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_recommendation_item_catalog_versions_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_versions_v1_catalog_id" ON "recommendation_item_catalog_versions_v1" ("catalogVersionId")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_versions_v1_sha256" ON "recommendation_item_catalog_versions_v1" ("payloadSha256")',
      `CREATE TABLE IF NOT EXISTS "recommendation_item_catalog_items_v1" (
        "id" SERIAL NOT NULL,
        "catalogVersionId" character varying(128) NOT NULL,
        "itemId" bigint NOT NULL,
        "name" character varying(255) NOT NULL,
        "className" character varying(255),
        "itemType" character varying(64),
        "slotType" character varying(64),
        "cost" integer,
        "tier" integer,
        "shopable" boolean,
        "disabled" boolean,
        "active" boolean,
        "isActiveItem" boolean,
        "activationType" character varying(64),
        "rawPayload" jsonb NOT NULL,
        CONSTRAINT "PK_recommendation_item_catalog_items_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_items_v1_version_item" ON "recommendation_item_catalog_items_v1" ("catalogVersionId", "itemId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_items_v1_catalog_id" ON "recommendation_item_catalog_items_v1" ("catalogVersionId")',
      `CREATE TABLE IF NOT EXISTS "recommendation_item_catalog_recipes_v1" (
        "id" SERIAL NOT NULL,
        "catalogVersionId" character varying(128) NOT NULL,
        "parentItemId" bigint NOT NULL,
        "componentItemId" bigint NOT NULL,
        "componentOrder" integer NOT NULL,
        CONSTRAINT "PK_recommendation_item_catalog_recipes_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_recipes_v1_parent_component" ON "recommendation_item_catalog_recipes_v1" ("catalogVersionId", "parentItemId", "componentItemId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_item_catalog_recipes_v1_catalog_id" ON "recommendation_item_catalog_recipes_v1" ("catalogVersionId")',
      `CREATE TABLE IF NOT EXISTS "recommendation_telemetry_events" (
        "eventId" character varying(128) NOT NULL,
        "deduplicationKey" character varying(512) NOT NULL,
        "schemaVersion" integer NOT NULL,
        "contractVersion" character varying(64) NOT NULL,
        "eventType" character varying(64) NOT NULL,
        "matchId" character varying(128) NOT NULL,
        "playerKey" character varying(255),
        "source" character varying(64) NOT NULL,
        "sourceEventId" character varying(255),
        "sourceOccurredAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "receivedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "gameTimeMs" integer,
        "sequenceNo" integer,
        "clientVersion" character varying(128) NOT NULL,
        "gepVersion" character varying(128) NOT NULL,
        "normalizerVersion" character varying(128) NOT NULL,
        "rulesetVersion" character varying(128) NOT NULL,
        "catalogSha256" character(64) NOT NULL,
        "directlyObserved" boolean NOT NULL,
        "reconstructed" boolean NOT NULL,
        "stale" boolean NOT NULL,
        "alignmentAgeMs" integer NOT NULL,
        "payload" jsonb NOT NULL,
        CONSTRAINT "PK_recommendation_telemetry_events" PRIMARY KEY ("eventId")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_telemetry_dedup_key" ON "recommendation_telemetry_events" ("deduplicationKey")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_telemetry_event_type" ON "recommendation_telemetry_events" ("eventType")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_telemetry_match_id" ON "recommendation_telemetry_events" ("matchId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_telemetry_source_occurred_at" ON "recommendation_telemetry_events" ("sourceOccurredAt")',
      `CREATE TABLE IF NOT EXISTS "recommendation_telemetry_rejections_v8" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "receivedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "eventId" character varying(128),
        "eventType" character varying(64),
        "matchId" character varying(128),
        "playerKey" character varying(255),
        "source" character varying(128),
        "runtimeMode" character varying(32),
        "errors" jsonb NOT NULL,
        CONSTRAINT "PK_recommendation_telemetry_rejections_v8" PRIMARY KEY ("id")
      )`,
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_telemetry_rejections_v8_received_at" ON "recommendation_telemetry_rejections_v8" ("receivedAt")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_telemetry_rejections_v8_runtime_mode" ON "recommendation_telemetry_rejections_v8" ("runtimeMode")',
      `CREATE TABLE IF NOT EXISTS "recommendation_decisions_v8" (
        "decisionId" character varying(128) NOT NULL,
        "eventId" character varying(128) NOT NULL,
        "matchId" character varying(128) NOT NULL,
        "playerKey" character varying(255) NOT NULL,
        "decidedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "gameTimeMs" integer,
        "stateRevision" character varying(128) NOT NULL,
        "candidateGeneratorVersion" character varying(128) NOT NULL,
        "rulesetVersion" character varying(128) NOT NULL,
        "catalogSha256" character(64) NOT NULL,
        "selectedActionKey" character varying(255) NOT NULL,
        "modelVersion" character varying(128) NOT NULL,
        "policyProbability" double precision NOT NULL,
        "experimentId" character varying(128),
        "experimentArm" character varying(128) NOT NULL,
        "assignmentVersion" character varying(128) NOT NULL,
        "armAssignmentPropensity" double precision NOT NULL,
        "actionLoggingPropensity" double precision NOT NULL,
        "randomized" boolean NOT NULL,
        "runtimeMode" character varying(32) NOT NULL,
        "fallbackUsed" boolean NOT NULL DEFAULT false,
        "fallbackReasons" jsonb NOT NULL DEFAULT '[]'::jsonb,
        "inferenceLatencyMs" double precision NOT NULL DEFAULT 0,
        "observedActionInjected" boolean NOT NULL DEFAULT false,
        CONSTRAINT "PK_recommendation_decisions_v8" PRIMARY KEY ("decisionId")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_decisions_v8_event_id" ON "recommendation_decisions_v8" ("eventId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_decisions_v8_match_id" ON "recommendation_decisions_v8" ("matchId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_decisions_v8_decided_at" ON "recommendation_decisions_v8" ("decidedAt")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_decisions_v8_runtime_mode" ON "recommendation_decisions_v8" ("runtimeMode")',
      `CREATE TABLE IF NOT EXISTS "recommendation_decision_candidates_v8" (
        "id" SERIAL NOT NULL,
        "decisionId" character varying(128) NOT NULL,
        "actionKey" character varying(255) NOT NULL,
        "actionType" character varying(64) NOT NULL,
        "targetItemId" bigint,
        "sellItemId" bigint,
        "recipeId" character varying(128),
        "consumedItemIds" jsonb,
        "effectiveCostSouls" integer NOT NULL,
        "spendableSoulsAfter" integer,
        "resultingItemIds" jsonb,
        "feasible" boolean NOT NULL,
        "feasibilityReasons" jsonb NOT NULL,
        "affordable" character varying(16) NOT NULL,
        "slotLegal" character varying(16) NOT NULL,
        "recipeLegal" character varying(16) NOT NULL,
        "shopLegal" character varying(16) NOT NULL,
        "rulesetLegal" character varying(16) NOT NULL,
        "transactionMechanicsKnown" boolean NOT NULL,
        "evidence" jsonb NOT NULL,
        "behaviorProbability" double precision,
        "policyScore" double precision,
        "valueScore" double precision,
        CONSTRAINT "PK_recommendation_decision_candidates_v8" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_decision_candidates_v8_decision_action" ON "recommendation_decision_candidates_v8" ("decisionId", "actionKey")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_decision_candidates_v8_decision_id" ON "recommendation_decision_candidates_v8" ("decisionId")',
      `CREATE TABLE IF NOT EXISTS "recommendation_evidence_snapshots_v8" (
        "subjectSha256" character(64) NOT NULL,
        "gateName" character varying(64) NOT NULL,
        "evaluator" character varying(256) NOT NULL,
        "evaluatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "report" jsonb NOT NULL,
        "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_recommendation_evidence_snapshots_v8" PRIMARY KEY ("subjectSha256")
      )`,
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_evidence_snapshots_v8_gate" ON "recommendation_evidence_snapshots_v8" ("gateName")',
      `CREATE TABLE IF NOT EXISTS "recommendation_exposure_acks_v8" (
        "eventId" character varying(128) NOT NULL,
        "decisionId" character varying(128) NOT NULL,
        "selectedActionKey" character varying(255) NOT NULL,
        "displayedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "displayOrder" jsonb NOT NULL,
        "ttlMs" integer NOT NULL,
        CONSTRAINT "PK_recommendation_exposure_acks_v8" PRIMARY KEY ("eventId")
      )`,
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_exposure_acks_v8_decision_id" ON "recommendation_exposure_acks_v8" ("decisionId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_exposure_acks_v8_displayed_at" ON "recommendation_exposure_acks_v8" ("displayedAt")',
      `CREATE TABLE IF NOT EXISTS "souls_affordability_evidence_v2" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "observationId" character varying(128) NOT NULL,
        "sessionId" character varying(128) NOT NULL,
        "rulesetVersion" character varying(128) NOT NULL,
        "catalogSha256" character(64) NOT NULL,
        "observation" jsonb NOT NULL,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_souls_affordability_evidence_v2" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_souls_affordability_evidence_v2_observation_id" ON "souls_affordability_evidence_v2" ("observationId")',
      'CREATE INDEX IF NOT EXISTS "idx_souls_affordability_evidence_v2_session_id" ON "souls_affordability_evidence_v2" ("sessionId")',
      'CREATE INDEX IF NOT EXISTS "idx_souls_affordability_evidence_v2_ruleset" ON "souls_affordability_evidence_v2" ("rulesetVersion")',
      'CREATE INDEX IF NOT EXISTS "idx_souls_affordability_evidence_v2_catalog" ON "souls_affordability_evidence_v2" ("catalogSha256")',
      `CREATE TABLE IF NOT EXISTS "model_bundle_registry_v1" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "modelId" character varying(128) NOT NULL,
        "modelVersion" character varying(128) NOT NULL,
        "manifestSha256" character(64) NOT NULL,
        "manifest" jsonb NOT NULL,
        "artifactBaseUri" character varying(1024) NOT NULL,
        "status" character varying(32) NOT NULL DEFAULT 'REGISTERED',
        "verification" jsonb,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "verifiedAt" TIMESTAMP WITH TIME ZONE,
        "activatedAt" TIMESTAMP WITH TIME ZONE,
        "retiredAt" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_model_bundle_registry_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_model_bundle_registry_v1_identity" ON "model_bundle_registry_v1" ("modelId", "modelVersion")',
      'CREATE INDEX IF NOT EXISTS "idx_model_bundle_registry_v1_model_id" ON "model_bundle_registry_v1" ("modelId")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_model_bundle_registry_v1_manifest_sha256" ON "model_bundle_registry_v1" ("manifestSha256")',
      'CREATE INDEX IF NOT EXISTS "idx_model_bundle_registry_v1_status" ON "model_bundle_registry_v1" ("status")',
      `CREATE TABLE IF NOT EXISTS "recommendation_dataset_registry_v1" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "datasetId" character varying(128) NOT NULL,
        "datasetSha256" character(64) NOT NULL,
        "manifestSha256" character(64) NOT NULL,
        "objectBaseUri" character varying(2048) NOT NULL,
        "manifest" jsonb NOT NULL,
        "status" character varying(32) NOT NULL DEFAULT 'REGISTERED',
        "verification" jsonb,
        "registeredAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "verifiedAt" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_recommendation_dataset_registry_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_dataset_registry_v1_dataset_id" ON "recommendation_dataset_registry_v1" ("datasetId")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_dataset_registry_v1_dataset_sha256" ON "recommendation_dataset_registry_v1" ("datasetSha256")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_dataset_registry_v1_manifest_sha256" ON "recommendation_dataset_registry_v1" ("manifestSha256")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_dataset_registry_v1_status" ON "recommendation_dataset_registry_v1" ("status")',
      `CREATE TABLE IF NOT EXISTS "recommendation_value_dataset_registry_v1" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "datasetId" character varying(128) NOT NULL,
        "datasetSha256" character(64) NOT NULL,
        "manifestSha256" character(64) NOT NULL,
        "objectBaseUri" character varying(2048) NOT NULL,
        "manifest" jsonb NOT NULL,
        "status" character varying(32) NOT NULL DEFAULT 'REGISTERED',
        "verification" jsonb,
        "registeredAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "verifiedAt" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_recommendation_value_dataset_registry_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_value_dataset_registry_v1_dataset_id" ON "recommendation_value_dataset_registry_v1" ("datasetId")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_value_dataset_registry_v1_dataset_sha256" ON "recommendation_value_dataset_registry_v1" ("datasetSha256")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_value_dataset_registry_v1_manifest_sha256" ON "recommendation_value_dataset_registry_v1" ("manifestSha256")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_value_dataset_registry_v1_status" ON "recommendation_value_dataset_registry_v1" ("status")',
      `CREATE TABLE IF NOT EXISTS "recommendation_roadmap_evidence_v1" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "evidenceId" character varying(128) NOT NULL,
        "gateName" character varying(64) NOT NULL,
        "status" character varying(32) NOT NULL,
        "evidenceRef" character varying(2048) NOT NULL,
        "evaluator" character varying(256) NOT NULL,
        "evaluatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "subjectSha256" character(64),
        "notes" text,
        "record" jsonb NOT NULL,
        "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_recommendation_roadmap_evidence_v1" PRIMARY KEY ("id")
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS "idx_recommendation_roadmap_evidence_v1_evidence_id" ON "recommendation_roadmap_evidence_v1" ("evidenceId")',
      'CREATE INDEX IF NOT EXISTS "idx_recommendation_roadmap_evidence_v1_gate" ON "recommendation_roadmap_evidence_v1" ("gateName")',
      `CREATE TABLE IF NOT EXISTS "statlocker_evidence_snapshots_v1" (
        "snapshotId" character varying(96) NOT NULL,
        "dataset" character varying(64) NOT NULL,
        "rulesetVersion" character varying(128) NOT NULL,
        "catalogSha256" character(64) NOT NULL,
        "statlockerPatchId" character varying(128) NOT NULL,
        "scopeKey" character varying(255) NOT NULL,
        "fetchedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "schemaVersion" character varying(64) NOT NULL,
        "collectorVersion" character varying(64) NOT NULL,
        "normalizerVersion" character varying(64) NOT NULL,
        "contentSha256" character(64) NOT NULL,
        "payload" jsonb NOT NULL,
        "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_statlocker_evidence_snapshots_v1" PRIMARY KEY ("snapshotId")
      )`,
      'CREATE INDEX IF NOT EXISTS "idx_statlocker_snapshot_lookup_v1" ON "statlocker_evidence_snapshots_v1" ("dataset", "rulesetVersion", "catalogSha256", "statlockerPatchId", "scopeKey", "fetchedAt")',
      `CREATE TABLE IF NOT EXISTS "adaptive_recommendation_decisions_v1" (
        "decisionId" character varying(128) NOT NULL,
        "matchId" character varying(128) NOT NULL,
        "playerKey" character varying(255) NOT NULL,
        "stateRevision" character(64) NOT NULL,
        "replayInput" jsonb NOT NULL,
        "result" jsonb NOT NULL,
        "decidedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        CONSTRAINT "PK_adaptive_recommendation_decisions_v1" PRIMARY KEY ("decisionId")
      )`,
      'CREATE INDEX IF NOT EXISTS "idx_adaptive_decisions_v1_match_player_time" ON "adaptive_recommendation_decisions_v1" ("matchId", "playerKey", "decidedAt")',
      'CREATE INDEX IF NOT EXISTS "idx_adaptive_decisions_v1_match_id" ON "adaptive_recommendation_decisions_v1" ("matchId")',
      'CREATE INDEX IF NOT EXISTS "idx_adaptive_decisions_v1_player_key" ON "adaptive_recommendation_decisions_v1" ("playerKey")',
      'CREATE INDEX IF NOT EXISTS "idx_adaptive_decisions_v1_state_revision" ON "adaptive_recommendation_decisions_v1" ("stateRevision")',
      'CREATE INDEX IF NOT EXISTS "idx_adaptive_decisions_v1_decided_at" ON "adaptive_recommendation_decisions_v1" ("decidedAt")',
    ];

    for (const statement of statements) {
      await queryRunner.query(statement);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const tables = [
      'adaptive_recommendation_decisions_v1',
      'statlocker_evidence_snapshots_v1',
      'recommendation_roadmap_evidence_v1',
      'recommendation_value_dataset_registry_v1',
      'recommendation_dataset_registry_v1',
      'model_bundle_registry_v1',
      'souls_affordability_evidence_v2',
      'recommendation_exposure_acks_v8',
      'recommendation_evidence_snapshots_v8',
      'recommendation_decision_candidates_v8',
      'recommendation_decisions_v8',
      'recommendation_telemetry_rejections_v8',
      'recommendation_telemetry_events',
      'recommendation_item_catalog_recipes_v1',
      'recommendation_item_catalog_items_v1',
      'recommendation_item_catalog_versions_v1',
    ];

    for (const tableName of tables) {
      await queryRunner.query(`DROP TABLE IF EXISTS "${tableName}"`);
    }
  }
}
